export const IMAGES = {
    //  Onboarding Background Images
    boarding1: require('./boarding1.png'),
    boarding2: require('./boarding2.png'),
    boarding3: require('./boarding3.png'),
    
    Bone: require('./Bone.png'),
    Paw: require('./Paw.png'),
    Logo: require('./Logo.png'),
    DoubleTick: require('./DoubleTick.png'),
    Email: require('./Email.png'),
    Lock: require('./Lock.png'),
    Image5: require('./Image5.png'),
    USer: require('./User.png'),
    EyeOff: require('./EyeOff.png'),
    EyeShow: require('./EyeShow.png'),
    Home: require('./Home.png'),
    Search: require('./Search.png'),
    Cart: require('./Cart.png'),
    Notification: require('./Notification.png'),
    BackArrow: require('./BackArrow.png'),
    SearchBlack: require('./SearchBlack.png'),
    CrossIcon: require('./CrossIcon.png'),
    Image1: require('./Image1.png'),
    Image2: require('./Image2.png'),
    Image3: require('./Image3.png'),
    Image4: require('./Image4.png'),
    Image6: require('./Image6.png'),
    DrawerMenu: require('./DrawerMenu.png'),
    Profile: require('./Profile.png'),
    DiscountPic: require('./DiscountPic.png'),
    PlaceOrder: require('./PlaceOrder.png'),
    ringImage: require('./ringImage.png'),
    catFood: require('./catFood.png'),
    HeartIcon: require('./heart.png'),
    ImageFrame: require('./imageFrame.png'),
    ArrowRightIcon: require('./arrowRight.png'),
    DrawerBg: require('./draweBg.png'),
    DrawerPaw: require('./Paw2.png'),
    DrawerBack: require('./DrawerArrow.png'),
}